# 03 Strategy

In [1]:
from pathlib import Path
import sys
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
if str(PROJECT_ROOT) not in sys.path: sys.path.append(str(PROJECT_ROOT))
print('Project root:', PROJECT_ROOT)
from src.features import load_latest_features
from src.strategy import MultiCryptoMomentumStrategy
data=load_latest_features().sort_values(['Datetime','symbol']).reset_index(drop=True)
print(data.shape)
data.head()

Project root: c:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system
(2626935, 27)

,Datetime,symbol,Open,High,Low,Close,Volume,quote_asset_volume,number_of_trades,taker_buy_base_volume,...,ma_96,ma_spread,vol_48,vol_288,volume_z_288,cs_momentum_rank,cs_vol_rank,raw_signal,signal_rank,target_next_ret
0,2021-01-02 00:00:00+00:00,BNBUSDT,37.7637,37.81560,37.5000,37.52930,1.124125e+04,4.229801e+05,1489,5.383601e+03,...,37.660184,-0.001411,0.001786,0.002331,0.362212,0.6,0.6,0.294937,0.6,0.001005
1,2021-01-02 00:00:00+00:00,BTCUSDT,29331.7000,29331.70000,29199.2200,29224.64000,2.831566e+02,8.287531e+06,5767,1.077721e+02,...,29195.599375,0.002827,0.001077,0.001802,0.638666,0.8,0.2,0.564847,0.8,0.002695
2,2021-01-02 00:00:00+00:00,ETHUSDT,728.9100,730.66000,723.9800,724.65000,6.862967e+03,4.993582e+06,3973,3.511280e+03,...,729.157917,0.000098,0.001347,0.001954,2.345262,0.4,0.4,0.268626,0.4,0.003105
3,2021-01-02 00:00:00+00:00,SOLUSDT,1.8421,1.84950,1.8065,1.80780,3.456661e+04,6.316727e+04,395,1.239531e+04,...,1.746895,0.034657,0.008562,0.007467,1.003428,1.0,1.0,0.597031,1.0,-0.001383
4,2021-01-02 00:00:00+00:00,XRPUSDT,0.2374,0.23767,0.2340,0.23441,5.311320e+06,1.253803e+06,2333,2.509631e+06,...,0.238282,-0.004166,0.003958,0.006330,0.028367,0.2,0.8,0.012273,0.2,0.004223

In [2]:
strategy=MultiCryptoMomentumStrategy(long_threshold=0.80,exit_threshold=0.55,max_symbols=2,base_order_notional=10000)
sample_time=data['Datetime'].iloc[1000]
market_slice=data[data['Datetime']==sample_time]
strategy.generate_signals_at_time(market_slice)

,Datetime,symbol,Close,signal,signal_rank,vol_288
1000,2021-01-02 16:40:00+00:00,BNBUSDT,37.93360,HOLD,0.6,0.002053
1001,2021-01-02 16:40:00+00:00,BTCUSDT,32583.98000,BUY,1.0,0.002553
1002,2021-01-02 16:40:00+00:00,ETHUSDT,773.90000,BUY,0.8,0.002632
1003,2021-01-02 16:40:00+00:00,SOLUSDT,1.75480,SELL,0.4,0.009114
1004,2021-01-02 16:40:00+00:00,XRPUSDT,0.21913,SELL,0.2,0.004949

In [3]:
positions={}
cash=100000
strategy.generate_orders(market_slice,positions,cash)

[{'timestamp': Timestamp('2021-01-02 16:40:00+0000', tz='UTC'),
  'symbol': 'BTCUSDT',
  'side': 'BUY',
  'qty': 0.3068992799529094,
  'price': 32583.98,
  'order_type': 'MARKET'},
 {'timestamp': Timestamp('2021-01-02 16:40:00+0000', tz='UTC'),
  'symbol': 'ETHUSDT',
  'side': 'BUY',
  'qty': 12.92156609381057,
  'price': 773.9,
  'order_type': 'MARKET'}]